# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: release

on:
  push:
    tags: [ "[0-9]+.[0-9]+.[0-9]+" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, 386, arm, arm64]
        os: [windows, linux, darwin]
        include:
          - ext: .exe
            os: windows
        exclude:
          - os: darwin
            arch: 386
          - os: darwin
            arch: arm
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Build ${{ matrix.os }} ${{ matrix.arch }}
      run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o bin/msm-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.ext }} -v ./... || true
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        path: bin/*

  pre-release:
    runs-on: ubuntu-latest
    needs: [test, build]
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.1
    - name: Release
      uses: fnkr/github-action-ghr@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GHR_PATH: artifact/
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
